{
 "title": "Waves2",
 "time": { "from": "2015-09-19T15:30:23.685Z", "to": "2015-09-19T21:38:02.852Z" },
 "templating": {
  "list": [
   {
    "name": "boatlengths",
    "query": "select boatResponse from spectrum WHERE boatLength ="
   }
  ]
 },
 "panels": [
  {
   "title": "Filtered Water Level",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "longAve" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "100" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Water Level (BHD in)" }
   ],
   "targets": [
    {
     "alias": "Water Level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "longAve" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Level Change Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Change Rate (in/hour)" }
   ],
   "targets": [
    {
     "alias": "5 min rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "changeRate5Minute" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Raw Water Level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "rawWaterLevel",
     "select": [
      [
       { "params": [ "waterLevel" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Wave Baseline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "waveBaseLine" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Ave Water Level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "longAve" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sea wave",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Wave height (Inches)" }
   ],
   "targets": [
    {
     "alias": "Sea wave",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "waveHeight" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filtered Sea Waves",
   "type": "graph",
   "description": "A filtered sea wave is a raw wave passed through a low pass filter to remove the high frequency components.",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Raw Wave",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "waveHeight" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Filtered Wave",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "waterLevel",
     "select": [
      [
       { "params": [ "filteredWaveHeight" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Abstacted Waves",
   "type": "graph",
   "description": "This shows the peak, period and power of individual waves abstracted from the water level data.",
   "gridPos": { "h": 16, "w": 21, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "wave",
     "select": [
      [
       { "params": [ "peak" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Period",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "wave",
     "select": [
      [
       { "params": [ "period" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "wave",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spectral response vs. Abstracted Wave Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Wave Power Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wavePowerNoise" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "cluster.wavePower",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wavePower" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "cluster.wavePowerAverage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wavePowerAve" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spectral Response by Wavelength",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "12" }
     ]
    },
    {
     "alias": "14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "14" }
     ]
    },
    {
     "alias": "16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "16" }
     ]
    },
    {
     "alias": "18",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "18" }
     ]
    },
    {
     "alias": "20",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "20" }
     ]
    },
    {
     "alias": "22",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "22" }
     ]
    },
    {
     "alias": "24",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "24" }
     ]
    },
    {
     "alias": "26",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "26" }
     ]
    },
    {
     "alias": "28",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "28" }
     ]
    },
    {
     "alias": "30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "30" }
     ]
    },
    {
     "alias": "32",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "32" }
     ]
    },
    {
     "alias": "34",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "34" }
     ]
    },
    {
     "alias": "36",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "36" }
     ]
    },
    {
     "alias": "38",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "38" }
     ]
    },
    {
     "alias": "40",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "40" }
     ]
    },
    {
     "alias": "42",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "42" }
     ]
    },
    {
     "alias": "44",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "44" }
     ]
    },
    {
     "alias": "46",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "46" }
     ]
    },
    {
     "alias": "48",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "48" }
     ]
    },
    {
     "alias": "50",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "spectrum",
     "select": [
      [
       { "params": [ "waveLengthResponse" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "waveLength", "operator": "=", "value": "50" }
     ]
    }
   ]
  },
  {
   "title": "Abstracted Wakes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Cluster Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wakeTotPower" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    },
    {
     "alias": "Wake Power Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wavePowerNoise" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wake distance, power and wavelength",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 101 },
   "targets": [
    {
     "alias": "Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wakeDistance" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Wake Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wakeTotPower" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Wake Wavelength",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster",
     "select": [
      [
       { "params": [ "wakeWavelength" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}